hiphopathy/models.py
from django.db import models
from django.forms import ModelForm, TextInput

# Create your models here.
class Artist(models.Model):
    artistid = models.IntegerField(primary_key=True)
    artist = models.CharField(max_length=765)
    alias = models.TextField()
    class Meta:
        db_table = u'artist'
    def __unicode__(self):
    	return self.artist
	
class Album(models.Model):
    albumid = models.IntegerField(primary_key=True)
    album = models.CharField(max_length=765)
    artistid = models.ForeignKey(Artist, db_column='artistid', to_field='artistid')
    class Meta:
        db_table = u'album'

class Song(models.Model):
    songid = models.IntegerField(primary_key=True)
    albumid = models.ForeignKey(Album, db_column='albumid', to_field='albumid')
    title = models.CharField(max_length=765)
    lyrics = models.TextField()
    artistid = models.ForeignKey(Artist, db_column='artistid', to_field='artistid')

    class Meta:
        db_table = u'song'
    def __unicode__(self):
    	return self.title
        
class Snippet(models.Model):
    snippetid = models.IntegerField(primary_key=True)
    songid = models.ForeignKey(Song, db_column='songid', to_field='songid')
    chunk = models.TextField()
    user_answer = models.CharField(max_length=765)
    decoded = models.CharField(max_length=765)
    comments = models.TextField()
    def __unicode__(self):
    	return self.chunk

class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        fields = ('user_answer', 'chunk')

hiphopathy/views.py
# Create your views here.

from django.shortcuts import get_object_or_404, render_to_response, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.forms.models import modelformset_factory
from django.core.mail import send_mail


from models import Artist
from models import Song
from models import Snippet
from models import SnippetForm
from contactform import ContactForm




def index(request):
    artist_list = Artist.objects.all().order_by('artist')
    return render_to_response('index.html', {'artist_list': artist_list},context_instance=RequestContext(request))
    
def search_form(request):
    return render_to_response('search_form.html',context_instance=RequestContext(request))
    
def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        snippet_list = Snippet.objects.filter(songid = q)
        return render_to_response('search_results.html',
        {'snippet_list': snippet_list, 'query': q}, context_instance=RequestContext(request))
    else:
        return render_to_response('search_form.html',context_instance=RequestContext(request))

    
def song_view(request, artistid):
    artist = Artist.objects.filter(artistid=artistid)
    song_list = Song.objects.filter(artistid=artistid)
    return render_to_response('song_index.html', {'song_list': song_list, 'artist': artist},context_instance=RequestContext(request))
    
    
def snippet_view(request, songid):
    song = Song.objects.filter(songid=songid)
    artist = song[0].artistid
    chunk_list = Snippet.objects.filter(songid = songid)
    return render_to_response('snippet_index.html', {'chunk_list': chunk_list, 'song': song, 'artist': artist}
    ,context_instance=RequestContext(request))
    

def post(request):
	if 'user_supplied_answer' in request.GET and request.GET['user_supplied_answer']:
		a = request.GET['user_supplied_answer']
		return render_to_response('snippet_post.html', {'answer': user_supplied_answer},context_instance=RequestContext(request))
	else:
		return HttpResponse('Bye')

def about(request):
    return render_to_response('about.html',context_instance=RequestContext(request))

def code(request):
    return render_to_response('code.html',context_instance=RequestContext(request))

def code2(request):
    return render_to_response('code2.html',context_instance=RequestContext(request))

def tutorial_1(request):
    return render_to_response('tutorial_1.html',context_instance=RequestContext(request))

def visual_score(request):
    return render_to_response('visual_score.html', context_instance=RequestContext(request))

def tutorial_2(request):
    artist_list = Artist.objects.all().order_by('artist')
    return render_to_response('tutorial_2.html', {'artist_list': artist_list},context_instance=RequestContext(request))

def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            topic = form.clean_data['topic']
            message = form.clean_data['message']
            sender = form.clean_data.get('sender', 'noreply@example.com')
            send_mail(
                       'Feedback from your site, topic: %s' % topic,
                       message, sender,
                       ['administrator@example.com']
            )
        return render(request,'index.html')
    else:
        form = ContactForm()
        return render(request,'contact.html',{'form':form})

def manage_snippets(request, snippetid):
    mymodel = get_object_or_404(Snippet, snippetid =snippetid )
    form = SnippetForm(request.POST or None, instance= mymodel)
    if form.is_valid():
        mymodel = form.save()
        mymodel.save()
        artist_list = Artist.objects.all().order_by('artist')
        return render_to_response('tutorial_2.html', {'artist_list': artist_list},context_instance=RequestContext(request))
    return render(request, "manage_snippets.html", {'form': form, 'mymodel':mymodel})

# What I need to do is get the first 4 snippets, assess them and then turn in into json and visualize it.
# Snippet.objects.all()[:4]

hiphopathy/templates/hiphopathy/about.html
{% extends "base.html" %}

{% block title %}Hiphopathy: Code{% endblock %}

{% block navbar %}
    <li><a href="/hiphopathy/">Home</a></li>
    <li><a href="/hiphopathy/code/">Code</a></li>
    <li class="active"><a href="/hiphopathy/about/">About</a></li>
    <li><a href="/hiphopathy/search_form/">Search</a></li>
    <li><a href="/hiphopathy/contact/">Contact</a></li>
{% endblock %}

{% block header %}Hiphopathy: About the Team{% endblock %}



{% block divider1 %}{% endblock %}
{% block divider2 %}{% endblock %}
{% block marketing %}
<div class="span12">
	<h3><a href="http://omojumiller.com" target="blank">Omoju Miller</a></h3>
    <p>Omoju is the lead researcher on the "Hiphopathy" project between UC Berkeley and the International Computer Science Institute, which uses artificial intelligence techniques to deepen our understanding of human cognition and reasoning in hiphop lyrics. She has an undergraduate degree in Computer Science (2001) and a Master's degree in Electrical and Computer Engineering (2004) from the University of Memphis. She has over a decade of experience in the technology industry. She is currently a doctoral student at UC Berkeley in Computer Science Education. Omoju also serves in a volunteer capacity as an advisor to the White House Presidential Innovation Fellows, where she focuses on inclusion and diversity in technology.</p>
	<div class="row-fluid">
	    <div class="span6">
			<h4><a href="http://alex.heartdrops.org/" target="blank">Alex Greenspan</a></h4>
		    <p>Alex is a sophomore at UC Berkeley, double majoring in computer science and cognitive science. She is passionate about her interdisciplinary studies and hopes to further her educational focus in either HCI, natural language processing, or computational neuroscience.</p>

		    <h4>Eric Chu</h4>
		    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		    <h4>Jordan Arnesen</h4>
		    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
		</div>

		<div class="span6">
			<h4>Daniel Hsu</h4>
		    <p>Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.</p>

		    <h4>Grayson Flood</h4>
		    <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.</p>

		    <h4>Kevin Funkhouser</h4>
		    <p>Maecenas sed diam eget risus varius blandit sit amet non magna.</p>
		</div>
	</div>
</div>
{% endblock %}

hiphopathy/templates/hiphopathy/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Hiphopathy{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/docs.css" rel="stylesheet">
    <link href="http://twitter.github.com/bootstrap/assets/js/google-code-prettify/prettify.css" rel="stylesheet">

<style type="text/css">

html, body {
  margin: 0%;
  padding-left: 0px;
  padding-right: 0px;
  font-family: 'Source Sans Pro', sans-serif;
  background: #FFF;
}

/*colored bar for top of page*/
#headerBar {
    height: 200px;
    /*background: #274F7D;*/
    position: absolute;
    top: 0;
    width: 100%;
    z-index: -1;
    /* fallback */
    background-color: #049cdb;
    /*background: url(images/linear_bg_2.png);
    background-repeat: repeat-x;*/

    /* Safari 4-5, Chrome 1-9 */
    background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#FFFFFF), to(#049cdb));

    /* Safari 5.1, Chrome 10+ */
    background: -webkit-linear-gradient(top, #049cdb, #FFFFFF);

    /* Firefox 3.6+ */
    background: -moz-linear-gradient(top, #049cdb, #FFFFFF);

    /* IE 10 */
    background: -ms-linear-gradient(top, #049cdb, #FFFFFF);

    /* Opera 11.10+ */
    background: -o-linear-gradient(top, #049cdb, #FFFFFF);
}

/* Jumbotrons
-------------------------------------------------- */

/* Base class
------------------------- */
.jumbotron {
  position: relative;
  padding: 20px 0;
  color: #fff;
  text-align: center;
  text-shadow: 0 1px 3px rgba(0,0,0,.4), 0 0 30px rgba(0,0,0,.075);
  background: #020031; /* Old browsers */
  background: -moz-linear-gradient(45deg,  #020031 0%, #6d3353 100%); /* FF3.6+ */
  background: -webkit-gradient(linear, left bottom, right top, color-stop(0%,#020031), color-stop(100%,#6d3353)); /* Chrome,Safari4+ */
  background: -webkit-linear-gradient(45deg, #049cdb 0%, #FFFFFF 100%); /* Chrome10+,Safari5.1+ */
  background: -o-linear-gradient(45deg,  #020031 0%,#6d3353 100%); /* Opera 11.10+ */
  background: -ms-linear-gradient(45deg,  #020031 0%,#6d3353 100%); /* IE10+ */
  background: linear-gradient(45deg,  #020031 0%,#6d3353 100%); /* W3C */
  filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#020031', endColorstr='#6d3353',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
  -webkit-box-shadow: inset 0 3px 7px rgba(0,0,0,.2), inset 0 -3px 7px rgba(0,0,0,.2);
     -moz-box-shadow: inset 0 3px 7px rgba(0,0,0,.2), inset 0 -3px 7px rgba(0,0,0,.2);
          box-shadow: inset 0 3px 7px rgba(0,0,0,.2), inset 0 -3px 7px rgba(0,0,0,.2);
}
.jumbotron h1 {
  padding: 20px 0;
  font-size: 60px;
  font-weight: bold;
  letter-spacing: -1px;
  line-height: 1;
}
.jumbotron h3 {
  padding: 0px 0;
  font-size: 28px;
  font-weight: bold;
  letter-spacing: -1px;
  line-height: 1;
}
.footer{
	background-color: #fbfbf0;
	border-top: 1px solid #fff;
	color: #323a3f;
	font-size: 16px;
	padding: 30px 0;
}

.footer-wrapper {
	margin: 0 auto;
	width: 960px;

	font-weight: 600;
}

/*made in brooklyn text*/
.footer-wrapper div{
	float: left;
	margin-left: 20px;
}

.footer ul {
	margin-right: 20px;
	text-align: right;
}
.footer ul li{
	display: inline-block;
	margin-left: 50px;
}

.footer ul li a{
	font-weight: normal;
	color: #767b82;
}
.footer ul li a:hover{
	color: #17a4cb;
}


.bottom-wrapper{
	height: 105px;
	border-bottom: 1px solid #dfe1e6;
	font-weight: 600;
}




.navbar-inner {
  min-height: 80px;
}

      .muted {
        color: #FFF;
      }

      .nav.nav-pills.pull-right a {
        color: #FFF;
      }

      .nav.nav-pills.pull-right a:hover {
        color: #08c;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        width: 50%;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }


.container {
   text-align: right;

}

      @font-face {
        font-family: Aaaiight;
        src: url('aaaiight-fat.ttf') format("truetype");
      }
      /* Supporting marketing content */

    .marketing {
    margin: 100px auto 0px auto;
    text-align: left;
    color: #5a5a5a;
    }
      .marketing p {
        font-size: 17px;
        line-height: 1.5;
      }
      .marketing p + h3 {
        margin-bottom: 60px;
      }
      .marketing p + h4 {
        margin-bottom: 20px;
      }

.mini-layout,
.mini-layout .mini-layout-body,
.mini-layout.fluid .mini-layout-sidebar {
    height: 500px;
}
.mini-layout {
    margin-bottom: 20px;
    padding: 9px;
}
.mini-layout div {
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
}
.mini-layout .mini-layout-body {
    background-color: #dceaf4;
    margin: 0 auto;
    width: 50%;
}
.mini-layout.fluid .mini-layout-sidebar,
.mini-layout.fluid .mini-layout-header,
.mini-layout.fluid .mini-layout-body {
    float: left;
}
.mini-layout.fluid .mini-layout-sidebar {
    background-color: #ddd8e9;
    width: 50%;
}
.mini-layout.fluid .mini-layout-body {
    width: 45.5%;
    margin-left: 2.5%;
}

    </style>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
  </head>
  <body>




  <div id="headerBar"></div>


   <!-- Navbar
    ================================================== -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="brand" href="/hiphopathy/">{% block header %}Hiphopathy{% endblock %}</a>
          <div class="nav-collapse collapse">
            <ul class="nav">  {% block navbar %}
              <li class="active">
                <a href="/hiphopathy/">Home</a>
              </li>
              <li class="">
                  <a href="/hiphopathy/tutorial_1/">Get Started</a>
              </li>
                <li class="">
                  <a href="/hiphopathy/code/">Code</a>
              </li>
              <li class="">
                <a href="/hiphopathy/about/">About</a>
              </li>
              <li class="">
                <a href="/hiphopathy/search_form/">Search</a>
              </li>
              <li class="">
               <a href="/hiphopathy/contact/">Contact</a>
              </li> {% endblock %}
            </ul>
          </div>
        </div>
      </div>
    </div>

  <img src="{{ STATIC_URL }}Media/transparent.gif" /> <br> <br>
  <img src="{{ STATIC_URL }}Media/transparent.gif" /> <br> <br>

     <div class="jumbotron">
        {% block jumbotron %}
        {% endblock %}
      </div>
      {% block divider2 %}<hr>{% endblock %}

    <div class="container">



      <div class="row-fluid span9 marketing">
        {% block marketing %}{% endblock %}
      </div>

    </div> <!-- /container -->


    <!-- Footer
    ================================================== -->
    {% block footer %}
   <img src="https://static0.datemyschool.com/809244/static/imgv3/css/field-info-arrow-down.png" style="display:none;" />

    <div class="footer">
        <div class="footer-wrapper">
            <div>
                Made in Berkeley
            </div>
            <ul class="footer-links">
                <li>&copy; Omoju Miller 2013</li>
            </ul>
        </div>
    </div>


     {% endblock %}
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <!-- // <script src="http://code.jquery.com/jquery.js"></script> -->
    <!-- // <script src="C:/hipopathy/hiphopathy//bootstrap/js/bootstrap.min.js"></script> -->
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>

  </body>
</html>

hiphopathy/templates/hiphopathy/code.html
<html>


 <head>
    <title>Hiphopathy - Code</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}bootstrap/css/docs.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}Scripts/dist/skulpt.min.js" type="text/javascript"></script> 
    <script src="{{ STATIC_URL }}Scripts/dist/skulpt-stdlib.js" type="text/javascript"></script>
    <!---
     <link href="{{ STATIC_URL }}css/codemirror.css" rel="stylesheet" type="text/css" media="all" >
    <link href="{{ STATIC_URL }}css/solarized.css" rel="stylesheet" type="text/css" media="all" >
    -->
    <script src="{{ STATIC_URL }}Scripts/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>

</head>



<body>


<div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="brand" href="/hiphopathy/">Build Something</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class=""><a href="/hiphopathy/">Home</a></li>
              <li class=""><a href="/hiphopathy/tutorial_1/">How To</a></li>
              <li class="active"><a href="/hiphopathy/code/">Code</a></li>
              <li class=""><a href="/hiphopathy/about/">About</a></li>
              <li class=""><a href="/hiphopathy/search_form/">Search</a></li>
              <li class=""><a href="/hiphopathy/contact/">Contact</a></li>
            </ul>
          </div>
        </div>
      </div>
 </div>

 <div class="jumbotron">
     <img src="{{ STATIC_URL }}Media/transparent.gif" /> <br>
 </div>




 <img src="{{ STATIC_URL }}Media/transparent.gif" /> <br><br>
 <img src="{{ STATIC_URL }}Media/transparent.gif" /> <br><br>
<script type="text/javascript">

// There is decent documentation at the following site: http://reputablejournal.com/post/14021555501/adding-a-module-to-skulpt
// output functions are configurable.  This one just appends some text
// to a pre element.
function outf(text) {
    var mypre = document.getElementById("output");
    mypre.innerHTML = mypre.innerHTML + text;
}
function builtinRead(x) {
    if (Sk.builtinFiles === undefined || Sk.builtinFiles["files"][x] === undefined)
            throw "File not found: '" + x + "'";
    return Sk.builtinFiles["files"][x];
}

// This is for the ace editor
    window.onload = function() {
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/python");
    };

// Here's everything you need to run a python program in skulpt
// grab the code from your textarea
// get a reference to your pre element for output
// configure the output function
// call Sk.importMainWithBody()
function runit() {
  // var prog = document.getElementById("yourcode").value;
   var prog = document.getElementById("editor").env.document.getValue()

   var mypre = document.getElementById("output");
   mypre.innerHTML = '';
   Sk.canvas = "mycanvas";
   Sk.pre = "output";
   Sk.configure({output:outf, read:builtinRead});

   try{
    Sk.importMainWithBody("<stdin>",false,prog);
   } catch(e) { 
    alert(e);
  }
   
}

//eval(Sk.importMainWithBody("<stdin>",false,prog));


</script>
<div class="span7">
<h3>Try This</h3>
</div>


<div class="span5">
<form>
    <button type="button" class="btn btn-info" onclick="runit()">Run</button>
</form>
<pre id="output" ></pre>
<!-- If you want turtle graphics include a canvas -->
<canvas id="mycanvas" height="200" width="400"></mycanvas>
</div>

<div id="editor">
import turtle
def drawSquare(t, sz):
    """Make turtle t draw a square of with side sz."""

    for i in range(4):
        t.forward(sz)
        t.left(90)

t = turtle.Turtle()

for c in ['blue', 'red', 'black', 'green', 'red']:
    t.color(c)
    t.forward(60)
    t.left(72)

t.color('blue') # change the color of the pen
t.circle(40) # draw a circle of radius 40

t.shape('turtle')
t.right(23)
t.color('black')
drawSquare(t, 100)

</div>



</body>
</html>

hiphopathy/templates/hiphopathy/code2.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Editor</title>
  <style type="text/css" media="screen">
    body {
        overflow: hidden;
    }
    .body{overflow:hidden; _overflow:visible; _zoom:1;}
        .page{margin: 0 auto; width: 750px;_text-align:left; padding-bottom:40px;}
        .main{overflow: hidden;_overflow:visible;_zoom:1;}

    #editor {
        margin: 0;
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        right: 0;
    }
  </style>
</head>
<body>

<div id="editor">function foo(items) {
    var i;
    for (i = 0; i &lt; items.length; i++) {
        alert("Ace Rocks " + items[i]);
    }
}</div>

<script src="{{ STATIC_URL }}Scripts/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/twilight");
    editor.getSession().setMode("ace/mode/javascript");
</script>

</body>
</html>

hiphopathy/templates/hiphopathy/index - Copy.html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Hiphopathy 	Empathy building through Linguistic Data Analysis</title>
    <link rel="stylesheet" type="text/css" media="screen,print" href="../mysite_hiphopathy/mysite/static/Welcome_2_files/Welcome_2-2.css" />
  </head>
  <body style="background: rgb(255, 255, 255); margin: 0pt;">
  
   
<div>
<p style="padding-top: 10pt; padding-left: 20pt">Hiphopathy: Empathy building through Linguistic Data Analysis</p>
</div>
            
        

<div>
<p style="padding-top: 20pt; padding-left: 20pt">
A tool that gives you the opportunity to test how much you are able to understand the cultural milieu of another person, 
by paying careful attention to language, the cultural frames they evoke, with the goal of maintaining thematic coherence.<br /></p>
<p><br /></p>
</div>
<div> 
    <ul>
	{% for artist in artist_list %}
		<li><a href="/hiphopathy/{{ artist.artistid }}/song_view/">{{ artist.artist }}</a></li>
	{% empty %}
		<p>No artist in the database.</p>
	{% endfor %}
	</ul>
</div>
           
  
  </body>
</html>

hiphopathy/templates/hiphopathy/tutorial_2.html
{% extends "base.html" %}

{% block title %}Hiphopathy: Example{% endblock %}


{% block navbar %}
<li><a href="/hiphopathy/">Home</a></li>
<li class="active"><a href="/hiphopathy/tutorial_1/">How To</a></li>
<li><a href="/hiphopathy/about/">About</a></li>
<li><a href="/hiphopathy/search_form/">Search</a></li>
<li><a href="/hiphopathy/contact/">Contact</a></li>
{% endblock %}


{% block header %} Tutorial {% endblock %}
{% block divider2 %}{% endblock %}

{%block jumbotron%}
    <div>

            <p>
            <h1>Algorithm</h1>
            </p>
    </div>
{% endblock %}

{% block marketing %}


<p>In order to solve a problem, a Computer Scientist has to figure out the series of steps that can be followed which will lead to
    a solution. These series of steps is called an algorithm. Our first attempt at that process is coming up with a decoding algorithm.
The table below is the results of our firs attempt.</p>
<p>
<table class="table table-condensed table-striped table-bordered">
    <caption>Decoding Algorithm</caption>
    <tbody>
     <tr>
        <td> Step </td>
        <td> Instruction</td>
    </tr>
    <tr>
        <td>1 </td>
        <td>Read the sentence(s) thoroughly</td>
    </tr>
    <tr>
        <td>2 </td>
        <td> Determine the context, if not given to you</td>

    </tr>
    <tr>
        <td>3</td>
        <td> Identify metaphors (distinguish between literal and metaphorical language in text). <br>

           <table class="table table-condensed table-striped table-bordered">
            <tbody>
            <tr>
                <td>
                    Use the abstraction process to decide which words to focus on
                </td>
            </tr>
            <tr>
                <td>
                    In our case, we will use an heuristic to focus our attention. Since one of the goals of
        this project is understanding how we reason about conceptual metaphors, we will use knowledge of conceptual
        metaphor research in natural language understanding to guide our solution<sup>1</sup>. In that field, they follow
        the heuristic of focusing on noun and verb phrases, with particular attention to action verbs.<br>
        <small class="pull-right">[1] E. Shutova. Models of Metaphor in NLP. Computational Linguistics, (July):688–697, 2010.</small>
                </td>
            </tr>
            </tbody>
        </table>

        </td>
    </tr>
    <tr>
        <td>4</td> <td>Try to identify the concepts that you think are involved in understanding the sentence.</td>
    </tr>

    </tbody>
</table>
</p>
<div class="bs-docs-example">
    <p>We need a place to
        <a href="#" id="focus1"
           class="label label-info"
           rel="popover"
           data-placement="top"
           data-original-title="Abstraction, focus on the action verb">pitch</a>
        we need a <a href="#" id="focus2"
                     class="label label-info"
                     rel="popover"
                     data-placement="top"
                     data-animantion="true"
                     data-original-title="Abstraction, focus on the noun">mound.</a>

        <div class="control-group">
            <label class="control-label"> Concepts:</label>
            <input id="id_user_answer" type="text" name="user_answer" value=" baseball, business " maxlength="765" />
        </div>
        <br>
        <div class="control-group">
            <div class="controls">
              <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </p>
</div>
<pre class="prettyprint"></pre>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-tooltip.js"></script>
<script src="/twitter-bootstrap/twitter-bootstrap-v2/js/bootstrap-popover.js"></script>
<script>
    $(function ()
    { $("#focus1").tooltip();
    });
    $(function ()
    { $("#focus2").tooltip();
    });
</script>



<a href="/hiphopathy/1/manage_snippets" class="btn btn-primary"> 1 snippet</a>
<a href="/hiphopathy/2/manage_snippets" class="btn btn-primary"> 2 snippet</a>
<a href="/hiphopathy/3/manage_snippets" class="btn btn-primary"> 3 snippet</a>
<a href="/hiphopathy/4/manage_snippets" class="btn btn-primary"> 4 snippet</a>
<a href="/hiphopathy/visual_score/" class="btn btn-primary"> Visualize Score</a>
{% endblock %}